---
kind: ConfigMap
apiVersion: v1
metadata:
  name: mysql-config
data:
  my.cnf: |-
    [mysqld]
    default_authentication_plugin=mysql_native_password
---
apiVersion: v1
kind: Secret
metadata:
  name: zabbix-mysql-root-password
data:
  password: bXktc3VwZXItc2VjcmV0LXBhc3M=
---
apiVersion: mysql.oracle.com/v1alpha1
kind: Cluster
metadata:
  name: mysql-zabbix
spec:
  members: 3
  config:
    name: mysql-config
  rootPasswordSecret:
    name: zabbix-mysql-root-password
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
      storageClassName: rook-ceph-block
