rbac:
  enabled: false
operator:
  global: true
  namespace: mysql-operator
  register_crd: true
image:
  tag: 0.2.0
  repository: iad.ocir.io/oracle/mysql-operator
  pullPolicy: IfNotPresent

mysql:
  server:
    image: mysql/mysql-server
  agent:
    image: iad.ocir.io/oracle/mysql-agent
